document.addEventListener("DOMContentLoaded", () => {
  // --- SUPABASE CONFIGURATION AND INITIALIZER ---
  let supabaseClient = null;

  // --- PRODUCTION CREDENTIALS ---
  // If you are ready to launch, paste your live Supabase credentials here:
  const PRODUCTION_SUPABASE_URL = "https://jwoyscbjyvmkekwwkbrn.supabase.co"; 
  const PRODUCTION_SUPABASE_ANON_KEY = "sb_publishable_FWPsXSQxNkR406JQivPooQ_t-6m-PHt";

  // Read config from localStorage if present, otherwise fallback to production keys
  let supabaseUrl = localStorage.getItem("supabase_url") || PRODUCTION_SUPABASE_URL;
  let supabaseAnonKey = localStorage.getItem("supabase_anon_key") || PRODUCTION_SUPABASE_ANON_KEY;

  const updateStatusIndicators = (isConnected) => {
    const pulses = document.querySelectorAll(".supabase-pulse-indicator");
    const pills = document.querySelectorAll(".supabase-status-pill");
    
    pulses.forEach(p => {
      if (isConnected) {
        p.classList.add("connected");
      } else {
        p.classList.remove("connected");
      }
    });

    pills.forEach(p => {
      if (isConnected) {
        p.textContent = "Connected";
        p.classList.add("connected");
      } else {
        p.textContent = "Disconnected";
        p.classList.remove("connected");
      }
    });
  };

  const initSupabase = () => {
    if (supabaseUrl && supabaseAnonKey && window.supabase) {
      try {
        supabaseClient = window.supabase.createClient(supabaseUrl, supabaseAnonKey);
        updateStatusIndicators(true);
      } catch (err) {
        console.error("Failed to initialize Supabase client:", err);
        supabaseClient = null;
        updateStatusIndicators(false);
      }
    } else {
      supabaseClient = null;
      updateStatusIndicators(false);
    }
  };

  const addConsoleLog = (message, type = "info") => {
    const logger = document.getElementById("supabase-console-logs");
    if (!logger) return;
    const entry = document.createElement("div");
    entry.className = `supabase-log-entry ${type}`;
    const now = new Date();
    const timeStr = now.toTimeString().split(' ')[0];
    entry.textContent = `[${timeStr}] ${message}`;
    logger.appendChild(entry);
    logger.scrollTop = logger.scrollHeight;
  };
  window.addConsoleLog = addConsoleLog; // Expose globally for error tracking

  const testConnectionSilently = async () => {
    if (!supabaseClient) return;
    try {
      const { error } = await supabaseClient.from("newsletter_subscribers").select("id").limit(1);
      if (error && error.code !== "PGRST116") {
        throw error;
      }
      updateStatusIndicators(true);
    } catch (err) {
      updateStatusIndicators(false);
    }
  };

  const testConnectionExposed = async () => {
    if (!supabaseClient) {
      addConsoleLog("Error: Supabase client not initialized. Enter keys and save first.", "error");
      return;
    }
    addConsoleLog("Database: Sending diagnostic ping to Supabase...", "info");
    
    try {
      const { error } = await supabaseClient.from("newsletter_subscribers").select("id").limit(1);
      if (error && error.code !== "PGRST116") {
        throw error;
      }

      addConsoleLog("Database Ping: Succeeded! Connection is verified and active.", "success");
      addConsoleLog("Check List: newsletter_subscribers table is accessible.", "success");
      updateStatusIndicators(true);
    } catch (err) {
      console.error(err);
      addConsoleLog(`Error: Connection failed. ${err.message || 'Check URL and Keys.'}`, "error");
      addConsoleLog(`Troubleshoot: Ensure you have executed the SQL Schema script to create the tables in your Supabase SQL editor.`, "info");
      updateStatusIndicators(false);
    }
  };

  const injectDeveloperConsole = () => {
    if (document.getElementById("supabase-console-drawer")) return; // Prevent double inject

    // 1. Create backdrop
    const backdrop = document.createElement("div");
    backdrop.className = "supabase-drawer-backdrop";
    backdrop.id = "supabase-console-backdrop";
    document.body.appendChild(backdrop);

    // 2. Create drawer container
    const drawer = document.createElement("div");
    drawer.className = "supabase-dev-drawer";
    drawer.id = "supabase-console-drawer";
    
    const sqlText = `-- Create contact requests table
create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  first_name text not null,
  email text not null,
  phone text,
  message text not null,
  budget text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create newsletter subscribers table
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create blogs table
create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null,
  category text not null,
  author text not null,
  content text not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create team roster members table
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  initials text not null,
  bg_color text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create developer portfolios table
create table if not exists public.portfolios (
  id bigint generated by default as identity primary key,
  name text not null,
  designation text not null,
  specialisation text not null,
  description text not null,
  photo_url text,
  github_url text,
  linkedin_url text,
  instagram_url text,
  portfolio_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on all tables
alter table public.contact_requests enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.blogs enable row level security;
alter table public.team_members enable row level security;
alter table public.portfolios enable row level security;

-- Create Public Insert Policies for Leads & Subscribers
create policy "Allow public inserts" on public.contact_requests for insert to anon, authenticated with check (true);
create policy "Allow public inserts" on public.newsletter_subscribers for insert to anon, authenticated with check (true);

-- Create Authenticated View & Delete Policies for Admin Panel
create policy "Allow auth select" on public.contact_requests for select to authenticated using (true);
create policy "Allow auth select" on public.newsletter_subscribers for select to authenticated using (true);
create policy "Allow auth delete" on public.contact_requests for delete to authenticated using (true);
create policy "Allow auth delete" on public.newsletter_subscribers for delete to authenticated using (true);

-- Create Public Read Policies for Blogs, Team, and Portfolios
create policy "Allow public select" on public.blogs for select to anon, authenticated using (true);
create policy "Allow public select" on public.team_members for select to anon, authenticated using (true);
create policy "Allow public select" on public.portfolios for select to anon, authenticated using (true);

-- Create Full CRUD Policies for Authenticated Admin Users
create policy "Allow auth CRUD" on public.blogs for all to authenticated using (true) with check (true);
create policy "Allow auth CRUD" on public.team_members for all to authenticated using (true) with check (true);
create policy "Allow auth CRUD" on public.portfolios for all to authenticated using (true) with check (true);`;

    drawer.innerHTML = `
      <div class="supabase-drawer-header">
        <h2 class="supabase-drawer-title">
          <span class="supabase-badge-icon">⚡</span> Supabase Dev Console
        </h2>
        <span class="supabase-drawer-close-btn" id="supabase-console-close">&times;</span>
      </div>

      <div class="supabase-status-banner">
        <span class="supabase-status-label">Database Status</span>
        <span class="supabase-status-pill">Disconnected</span>
      </div>

      <div class="supabase-drawer-form-group">
        <label class="supabase-drawer-label" for="supabase-url-input">Supabase Project URL</label>
        <input type="text" id="supabase-url-input" class="supabase-drawer-input" placeholder="https://your-project.supabase.co" value="${supabaseUrl}">
      </div>

      <div class="supabase-drawer-form-group">
        <label class="supabase-drawer-label" for="supabase-key-input">Anon API Key</label>
        <input type="password" id="supabase-key-input" class="supabase-drawer-input" placeholder="your-anon-api-key" value="${supabaseAnonKey}">
      </div>

      <div class="supabase-btn-group">
        <button class="supabase-drawer-btn supabase-drawer-btn-secondary" id="supabase-test-connection-btn">Test Server</button>
        <button class="supabase-drawer-btn supabase-drawer-btn-primary" id="supabase-save-config-btn">Save Key</button>
      </div>

      <div class="supabase-accordion-container" id="supabase-sql-accordion">
        <div class="supabase-accordion-trigger">SQL Schema Setup Script</div>
        <div class="supabase-accordion-content">
          <div class="supabase-accordion-inner">
            <button class="supabase-copy-btn" id="supabase-sql-copy-btn">Copy</button>
            <pre class="supabase-sql-pre"><code>${sqlText}</code></pre>
          </div>
        </div>
      </div>

      <label class="supabase-drawer-label">Connection Logs</label>
      <div class="supabase-log-container" id="supabase-console-logs">
        <div class="supabase-log-entry info">System: Developer Console initialized. Ready for credentials.</div>
      </div>
    `;
    document.body.appendChild(drawer);

    // 3. Create floating trigger badge
    const badge = document.createElement("div");
    badge.className = "supabase-dev-badge";
    badge.id = "supabase-console-trigger";
    badge.innerHTML = `
      <span class="supabase-pulse-indicator"></span>
      <span class="supabase-badge-icon">🗄️</span>
      <span class="supabase-badge-text">Supabase Config</span>
    `;
    document.body.appendChild(badge);

    // Attach listeners
    const triggerBtn = document.getElementById("supabase-console-trigger");
    const closeBtn = document.getElementById("supabase-console-close");
    const backdropEl = document.getElementById("supabase-console-backdrop");
    const drawerEl = document.getElementById("supabase-console-drawer");

    const openDrawer = () => {
      drawerEl.classList.add("open");
      backdropEl.classList.add("active");
    };

    const closeDrawer = () => {
      drawerEl.classList.remove("open");
      backdropEl.classList.remove("active");
    };

    triggerBtn.addEventListener("click", openDrawer);
    closeBtn.addEventListener("click", closeDrawer);
    backdropEl.addEventListener("click", closeDrawer);

    // Accordion Toggle
    const accordion = document.getElementById("supabase-sql-accordion");
    const accordionTrigger = accordion.querySelector(".supabase-accordion-trigger");
    accordionTrigger.addEventListener("click", () => {
      accordion.classList.toggle("expanded");
    });

    // Copy SQL script
    const copyBtn = document.getElementById("supabase-sql-copy-btn");
    copyBtn.addEventListener("click", () => {
      navigator.clipboard.writeText(sqlText).then(() => {
        copyBtn.textContent = "Copied!";
        setTimeout(() => copyBtn.textContent = "Copy", 2000);
        addConsoleLog("System: SQL setup script copied to clipboard.", "info");
      }).catch(err => {
        console.error("Failed to copy text:", err);
      });
    });

    // Save Credentials
    const saveBtn = document.getElementById("supabase-save-config-btn");
    saveBtn.addEventListener("click", () => {
      const urlVal = document.getElementById("supabase-url-input").value.trim();
      const keyVal = document.getElementById("supabase-key-input").value.trim();

      if (!urlVal || !keyVal) {
        addConsoleLog("Error: Both Supabase URL and Anon Key are required.", "error");
        return;
      }

      localStorage.setItem("supabase_url", urlVal);
      localStorage.setItem("supabase_anon_key", keyVal);
      supabaseUrl = urlVal;
      supabaseAnonKey = keyVal;

      initSupabase();

      addConsoleLog("Success: Saved credentials to local storage. Initializing connection...", "success");
      testConnectionSilently();
    });

    // Test Connection
    const testBtn = document.getElementById("supabase-test-connection-btn");
    testBtn.addEventListener("click", testConnectionExposed);

    // Auto test connection if keys exist
    if (supabaseUrl && supabaseAnonKey) {
      testConnectionSilently();
    }
  };

  // Run Supabase initialization and console injection on load
  initSupabase();
  // injectDeveloperConsole();

  // --- STATE AND PAGE INITIALIZERS ---
  const initPageLogic = () => {
    // 1. Card hover mouse coordinate tracking
    const cards = document.querySelectorAll(".card, .pricing-card");
    cards.forEach(card => {
      card.addEventListener("mousemove", (e) => {
        const rect = card.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        card.style.setProperty("--mouse-x", `${x}px`);
        card.style.setProperty("--mouse-y", `${y}px`);
      });
    });

    // 2. Contact budget selectors
    const budgetTags = document.querySelectorAll(".budget-tag");
    const budgetInput = document.getElementById("budgetSelected");
    if (budgetTags.length > 0 && budgetInput) {
      budgetTags.forEach(tag => {
        tag.addEventListener("click", () => {
          budgetTags.forEach(t => t.classList.remove("active"));
          tag.classList.add("active");
          budgetInput.value = tag.getAttribute("data-value");
        });
      });
    }

    // 3. Contact form submissions with Supabase Connection
    const contactForm = document.getElementById("contactFormElement");
    if (contactForm) {
      contactForm.addEventListener("submit", async (e) => {
        e.preventDefault();
        const firstName = document.getElementById("firstName")?.value.trim();
        const email = document.getElementById("email")?.value.trim();
        const message = document.getElementById("message")?.value.trim();
        const phone = document.getElementById("phone")?.value.trim() || "";
        const budget = budgetInput ? budgetInput.value : "None Selected";

        if (firstName && email && message) {
          if (supabaseClient) {
            showToast("Submitting request...");
            try {
              const { error } = await supabaseClient.from("contact_requests").insert([
                { first_name: firstName, email: email, phone: phone, message: message, budget: budget }
              ]);

              if (error) throw error;

              showToast(`Thank you, ${firstName}! Your request is saved in Supabase.`);
              contactForm.reset();
              budgetTags.forEach(t => t.classList.remove("active"));
              if (budgetInput) budgetInput.value = "";
              addConsoleLog(`Submissions: Contact request from ${firstName} (${email}) saved.`, "success");
            } catch (err) {
              console.error(err);
              showToast("Supabase Error: Submission failed. Check logs.");
              addConsoleLog(`Submission Failed: ${err.message || err}`, "error");
            }
          } else {
            showToast(`Thank you, ${firstName}! Your consultation request has been received.`);
            contactForm.reset();
            budgetTags.forEach(t => t.classList.remove("active"));
            if (budgetInput) budgetInput.value = "";
            addConsoleLog(`Warning: Submitting locally because Supabase is not configured.`, "info");
          }
        } else {
          showToast("Please fill in all required fields.");
        }
      });
    }



    // 5. Dynamic database portals fetches
    fetchAndRenderBlogs();
    fetchAndRenderTeam();
    fetchAndRenderPortfolios();
  };

  // --- TOAST NOTIFICATION TRIGGER ---
  const showToast = (message) => {
    let toast = document.querySelector(".toast");
    if (!toast) {
      toast = document.createElement("div");
      toast.className = "toast";
      toast.innerHTML = `
        <span class="toast-icon">✓</span>
        <span class="toast-text"></span>
      `;
      document.body.appendChild(toast);
    }
    
    toast.querySelector(".toast-text").textContent = message;
    toast.classList.add("show");

    setTimeout(() => {
      toast.classList.remove("show");
    }, 4000);
  };

  // --- UNIVERSAL INTERACTIVE UI CONTROLS ---

  // Header Scroll Shrink effect
  const header = document.querySelector(".header");
  window.addEventListener("scroll", () => {
    if (window.scrollY > 50) {
      header.classList.add("scrolled");
    } else {
      header.classList.remove("scrolled");
    }
  });

  // Mobile navigation drawer toggle controls
  const menuToggle = document.getElementById("menuToggle");
  const mobileDrawer = document.getElementById("mobileDrawer");
  const drawerClose = document.getElementById("drawerClose");
  const drawerBackdrop = document.getElementById("drawerBackdrop");
  
  const closeDrawer = () => {
    if (mobileDrawer) mobileDrawer.classList.remove("open");
    if (drawerBackdrop) drawerBackdrop.classList.remove("active");
    document.body.style.overflow = "";
  };

  if (menuToggle && mobileDrawer && drawerClose && drawerBackdrop) {
    menuToggle.addEventListener("click", () => {
      mobileDrawer.classList.add("open");
      drawerBackdrop.classList.add("active");
      document.body.style.overflow = "hidden";
    });
    drawerClose.addEventListener("click", closeDrawer);
    drawerBackdrop.addEventListener("click", closeDrawer);
  }

  // Full-screen search overlay control mechanisms
  const searchOverlay = document.getElementById("searchOverlay");
  const searchClose = document.getElementById("searchClose");
  const searchInput = document.getElementById("searchOverlayInput");

  const closeSearch = () => {
    if (searchOverlay) searchOverlay.classList.remove("open");
    document.body.style.overflow = "";
  };

  // Intercept any click of class `.search-trigger`
  document.addEventListener("click", (e) => {
    const trigger = e.target.closest(".search-trigger");
    if (trigger) {
      e.preventDefault();
      if (searchOverlay) {
        searchOverlay.classList.add("open");
        document.body.style.overflow = "hidden";
        setTimeout(() => searchInput && searchInput.focus(), 300);
      }
    }
  });

  if (searchClose) {
    searchClose.addEventListener("click", closeSearch);
  }
  window.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && searchOverlay && searchOverlay.classList.contains("open")) {
      closeSearch();
    }
  });

  // --- DYNAMIC CLIENT-SIDE ROUTER (SPA PJAX) ---
  const mainContent = document.getElementById("main");
  const updateActiveNavigationLinks = (currentUrl) => {
    const filename = currentUrl.substring(currentUrl.lastIndexOf('/') + 1) || "index.html";
    
    // Header Navigation Links
    const navLinks = document.querySelectorAll(".nav-link");
    navLinks.forEach(link => {
      const href = link.getAttribute("href");
      if (href === filename) {
        link.classList.add("active");
      } else {
        link.classList.remove("active");
      }
    });

    // Mobile Navigation Links
    const mobLinks = document.querySelectorAll(".mobile-nav-link");
    mobLinks.forEach(link => {
      const href = link.getAttribute("href");
      if (href === filename) {
        link.classList.add("active");
      } else {
        link.classList.remove("active");
      }
    });

    // Dynamic Header Page Indicator
    let pageName = "Home";
    if (filename.includes("services")) pageName = "Services";
    else if (filename.includes("about")) pageName = "About";
    else if (filename.includes("portfolio")) pageName = "Portfolio";
    else if (filename.includes("news")) pageName = "News";
    else if (filename.includes("contact")) pageName = "Contact";
    
    const indicators = document.querySelectorAll(".current-page-indicator");
    indicators.forEach(ind => {
      ind.textContent = pageName;
    });
  };

  const navigateToPage = async (url) => {
    try {
      // Add visual main container loading fade-out class
      mainContent.style.transition = "opacity 0.2s ease, transform 0.2s ease";
      mainContent.style.opacity = "0";
      mainContent.style.transform = "translateY(10px)";
      
      // Fetch page content
      const response = await fetch(url);
      if (!response.ok) throw new Error("Network request failed.");
      
      const htmlText = await response.text();
      
      // Parse fetched HTML text structures
      const parser = new DOMParser();
      const newDoc = parser.parseFromString(htmlText, "text/html");
      const newMain = newDoc.getElementById("main");
      const newTitle = newDoc.title;
      
      if (!newMain) throw new Error("Malformed HTML layout.");

      // Delay briefly to allow complete fade-out transitions
      setTimeout(() => {
        // Swap core main structures
        mainContent.innerHTML = newMain.innerHTML;
        document.title = newTitle;
        
        // Swap page-specific styles dynamically to prevent unstyled layouts
        const newStyle = newDoc.querySelector("head style");
        const currentStyle = document.querySelector("head style");
        if (newStyle && currentStyle) {
          currentStyle.innerHTML = newStyle.innerHTML;
        } else if (newStyle) {
          const clonedStyle = newStyle.cloneNode(true);
          document.head.appendChild(clonedStyle);
        } else if (currentStyle) {
          currentStyle.innerHTML = "";
        }
        
        // Scroll back to peak coordinate
        window.scrollTo({ top: 0, behavior: 'instant' });
        
        // Update active classes
        updateActiveNavigationLinks(url);
        
        // Re-execute page visual hooks
        initPageLogic();

        // Animate Page Fade-In
        mainContent.style.opacity = "1";
        mainContent.style.transform = "translateY(0)";
      }, 200);

    } catch (error) {
      console.error("PJAX Routing failure, falling back to full load: ", error);
      window.location.href = url; // Fallback to standard HTTP redirect
    }
  };

  // Global anchor click listener for client side navigation
  document.addEventListener("click", (e) => {
    const anchor = e.target.closest("a");
    if (!anchor) return;

    const href = anchor.getAttribute("href");
    
    // Bypass anchors that are just hashes, target blank, external URLs, or mailto/tel links
    if (!href || 
        href.startsWith("#") || 
        anchor.target === "_blank" || 
        href.startsWith("mailto:") || 
        href.startsWith("tel:") ||
        href.includes("://") && !href.startsWith(window.location.origin)) {
      return;
    }

    e.preventDefault();
    
    // Close overlay triggers on transitions
    closeDrawer();
    closeSearch();

    // Push State & Navigate
    history.pushState(null, '', href);
    navigateToPage(href);
  });

  // Handle standard browser Back/Forward pops
  window.addEventListener("popstate", () => {
    navigateToPage(window.location.pathname);
  });

  // --- DYNAMIC DATABASE PORTALS FETCHERS ---

  // 1. Fetch & Render Blogs
  const fetchAndRenderBlogs = async () => {
    const grid = document.getElementById("blogGrid");
    if (!grid) return;

    const renderMockBlogs = () => {
      grid.innerHTML = `
        <div class="empty-state" style="grid-column: 1 / -1; text-align: center; color: var(--text-secondary); padding: 60px 40px; border: 1px dashed var(--border-color); border-radius: var(--border-radius-md); background: rgba(255, 255, 255, 0.01); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;">
          <div style="font-size: 32px;">✍️</div>
          <h3 style="margin: 0; font-size: 18px; color: var(--text-primary);">No Blog Articles Published Yet</h3>
          <p style="margin: 0; font-size: 14px; color: var(--text-muted); max-width: 320px;">Real-time articles added via the Admin Console will dynamically populate this space.</p>
        </div>
      `;
    };

    if (!supabaseClient) {
      renderMockBlogs();
      return;
    }

    try {
      const { data, error } = await supabaseClient
        .from("blogs")
        .select("*")
        .order("created_at", { ascending: false });

      if (error || !data || data.length === 0) {
        renderMockBlogs();
        return;
      }

      grid.innerHTML = "";
      data.forEach(post => {
        const article = document.createElement("article");
        article.className = "blog-card";
        const date = new Date(post.created_at).toLocaleDateString("en-US", {
          month: "long",
          day: "numeric",
          year: "numeric"
        });

        // Set hover mouse coordinate listener on new card
        article.addEventListener("mousemove", (e) => {
          const rect = article.getBoundingClientRect();
          article.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`);
          article.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`);
        });

        article.innerHTML = `
          <div class="blog-image" style="background-image: url('${post.image_url}');">
            <span class="blog-category">${post.category}</span>
          </div>
          <div class="blog-content">
            <span class="blog-meta">${date} • By ${post.author}</span>
            <h3><a href="#">${post.title}</a></h3>
            <p>${post.subtitle}</p>
            <a href="#" class="blog-link">Read Article &rarr;</a>
          </div>
        `;
        grid.appendChild(article);
      });
    } catch (err) {
      console.error(err);
      renderMockBlogs();
    }
  };

  // 2. Fetch & Render Team
  const fetchAndRenderTeam = async () => {
    const grid = document.getElementById("teamGrid");
    if (!grid) return;

    const renderMockTeam = () => {
      grid.innerHTML = `
        <div class="empty-state" style="grid-column: 1 / -1; text-align: center; color: var(--text-secondary); padding: 60px 40px; border: 1px dashed var(--border-color); border-radius: var(--border-radius-md); background: rgba(255, 255, 255, 0.01); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;">
          <div style="font-size: 32px;">👥</div>
          <h3 style="margin: 0; font-size: 18px; color: var(--text-primary);">No Roster Members Added Yet</h3>
          <p style="margin: 0; font-size: 14px; color: var(--text-muted); max-width: 320px;">Use the Admin Console to add expert software developers and architects to your team roster.</p>
        </div>
      `;
    };

    if (!supabaseClient) {
      renderMockTeam();
      return;
    }

    try {
      const { data, error } = await supabaseClient
        .from("team_members")
        .select("*")
        .order("created_at", { ascending: true });

      if (error || !data || data.length === 0) {
        renderMockTeam();
        return;
      }

      grid.innerHTML = "";
      data.forEach(member => {
        const card = document.createElement("div");
        card.className = "team-card";
        
        card.addEventListener("mousemove", (e) => {
          const rect = card.getBoundingClientRect();
          card.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`);
          card.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`);
        });

        card.innerHTML = `
          <div class="expert-avatar" style="background: radial-gradient(circle, ${member.bg_color} 0%, #0c0c0c 100%); border: 2px solid var(--accent-neon);">${member.initials}</div>
          <div class="team-name">${member.name}</div>
          <div class="team-role">${member.role}</div>
        `;
        grid.appendChild(card);
      });
    } catch (err) {
      console.error(err);
      renderMockTeam();
    }
  };

  // 3. Fetch & Render Portfolios
  const fetchAndRenderPortfolios = async () => {
    const grid = document.getElementById("portfolioGrid");
    if (!grid) return;

    const renderMockPortfolios = () => {
      grid.innerHTML = `
        <div class="empty-state" style="grid-column: 1 / -1; text-align: center; color: var(--text-secondary); padding: 60px 40px; border: 1px dashed var(--border-color); border-radius: var(--border-radius-md); background: rgba(255, 255, 255, 0.01); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;">
          <div style="font-size: 32px;">💼</div>
          <h3 style="margin: 0; font-size: 18px; color: var(--text-primary);">No Developer Portfolios Added Yet</h3>
          <p style="margin: 0; font-size: 14px; color: var(--text-muted); max-width: 320px;">Use the Admin Console to register developers, details, skills, and links to publish portfolios.</p>
        </div>
      `;
    };

    if (!supabaseClient) {
      renderMockPortfolios();
      return;
    }

    try {
      const { data, error } = await supabaseClient
        .from("portfolios")
        .select("*")
        .order("created_at", { ascending: false });

      if (error || !data || data.length === 0) {
        renderMockPortfolios();
        return;
      }

      grid.innerHTML = "";
      data.forEach(port => {
        const card = document.createElement("div");
        card.className = "portfolio-card";
        
        card.addEventListener("mousemove", (e) => {
          const rect = card.getBoundingClientRect();
          card.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`);
          card.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`);
        });

        // Generate initials for avatar fallback
        const initials = port.name
          .split(" ")
          .map(n => n[0])
          .join("")
          .toUpperCase()
          .substring(0, 3);

        const avatarMarkup = port.photo_url 
          ? `<img src="${port.photo_url}" alt="${port.name}">` 
          : `<div class="portfolio-default-avatar">${initials}</div>`;

        // Generate specialisation tags
        const tags = port.specialisation
          .split(",")
          .map(t => `<span class="specialisation-tag">${t.trim()}</span>`)
          .join("");

        card.innerHTML = `
          <div class="portfolio-photo-frame">
            ${avatarMarkup}
          </div>
          <div class="portfolio-details">
            <div class="portfolio-name">${port.name}</div>
            <div class="portfolio-designation">${port.designation}</div>
            <div class="specialisation-tags">
              ${tags}
            </div>
            <div class="portfolio-bio">${port.description}</div>
            <div class="portfolio-socials">
              ${port.instagram_url !== '#' ? `
              <a href="${port.instagram_url}" class="portfolio-social-link" target="_blank" aria-label="Instagram">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>
              </a>` : ''}
              ${port.linkedin_url !== '#' ? `
              <a href="${port.linkedin_url}" class="portfolio-social-link" target="_blank" aria-label="LinkedIn">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>
              </a>` : ''}
              ${port.github_url !== '#' ? `
              <a href="${port.github_url}" class="portfolio-social-link" target="_blank" aria-label="GitHub">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
              </a>` : ''}
              ${port.portfolio_url !== '#' ? `
              <a href="${port.portfolio_url}" class="portfolio-social-link" target="_blank" aria-label="Portfolio">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>
              </a>` : ''}
            </div>
          </div>
        `;
        grid.appendChild(card);
      });
    } catch (err) {
      console.error(err);
      renderMockPortfolios();
    }
  };

  // Initialize page-specific details on original page load
  initPageLogic();
  updateActiveNavigationLinks(window.location.pathname);
});
